name: Spellcheck Files

on:
  push:
    branches:
      - main
    paths:
      - '**.md'
      - '.github/workflows/spellcheck.yaml'
  pull_request:
    branches:
      - main
    paths:
      - '**.md'
      - '.github/workflows/spellcheck.yaml'

jobs:
  spellcheck:
    name: Check spelling on Markdown
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: rojopolis/spellcheck-github-actions@0.17.0
      name: Spellcheck
      continue-on-error: true
      with:
        config_path: config/.spellcheck.yaml # put path to configuration file her
        task_name: Markdown