name: Spellcheck Files

on:
  push:
    branches:
      - main
    paths:
      - '**.md'
      - '.github/workflows/spellcheck.yaml'
  pull_request:
    branches:
      - main
    paths:
      - '**.md'
      - '.github/workflows/spellcheck.yaml'

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: rojopolis/spellcheck-github-actions@0.17.0
      name: Spellcheck
      with:
        task_name: Markdown